Fix dups in firstinitmarket
AyalaBadash/market_2022 pull request #312
Opened 2022-06-14 09:03 UTC by BARDAMRI

2022-06-14 11:26 UTC, livneido1 requested changes
- [ ] i dont understand the override boolean in setService
- [ ] i dont understand the tests you changed. did you changed them to notification tests? where? what about names?

2022-06-14 15:08 UTC, BARDAMRI commented
The changes are for the change of the boolean args we removed and also for the test who didn't pass because of miss-writing

2022-06-16 15:23 UTC, merged

2022-06-16 15:24 UTC, livneido1 approved these changes

2022-06-16 15:24 UTC, livneido1 approved these changes

2022-06-16 15:24 UTC, livneido1 approved these changes